version: ~> 1.0
sudo: false
language: node_js
node_js:
  - '10'
  - '12'
  - '14'
  - '15'
matrix:
  fast_finish: true
  allow_failures: []
cache: npm
install:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-install.bash)"
before_script:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-verify.bash)"
after_success:
  - >-
    eval "$(curl -fsSL
    https://raw.githubusercontent.com/bevry/awesome-travis/master/scripts/node-publish.bash)"
notifications:
  email:
    recipients: >-
      kxXns22XdBDU0dqnirvnoOg47xuchdLIMWJ0+UY95xSP1ZVcm3+74At+raYVsqLDVkHbDkr2pomPbWmVp62NywkAD0WI0GO5ACVT4KftAOF1Fzqu5+J1uuCTuRDkny/isFaymXDoPiBBrG6mktj3VS2JAOq8IWPaDp2wtdv6PvBn+sBhJnuZ67Jr3EGELsXYXmojN+S1tNU8IqlgcAcSqx/9TUfoqRTO5h/c/MqNNfPnbOkHkWEPK6brb6BQr/kZ/ZAFQEjnBrANuALyfy2EqsO+QxlihDImrN4EYXJAssj7ZXn7uwT+EzBO1GK+6jhJTJKpgcYXczkStwgKI0gd0kI7/uA8TliDWr6Sld69To9E85AYfjCYyRKtQ4vaJ6Ju8KbZnsS3UXdsLYw8HmVsFTFM+oqeamPxgtx8mu28YkkTJ2VZVU9KHjz+Vq1HEucwLwGjAyD2KWma7DW2DlBGbtYwi9w9gJxkGGkIx2Rcu8oVLX+wj0gebehnYu1erWNZi46VeVwzY0LbyqJoRV0xEGjhAxR16Z4i3UVpomApAfPKMiu+OW9adnuIawTAUo1BNReIetdJXRwNYTiJnmIcLBsc+9P/SrbTECWGywmJxDm3/M06NvrpEWbhdzw1YraihcbtluS6i8qH0z1ERjmlypVKpch116/hhMRzuYYRkLQ=
